name: al_ghafar_chakki
description: "A new Flutter shop management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4

  # Hardware & Scanner
  mobile_scanner: ^6.0.4
  qr_flutter: ^4.1.0

  # Thermal Printing & PDF Generation
  printing: ^5.13.3
  pdf: ^3.11.1

  # Communication, Formatting & State Management
  url_launcher: ^6.3.1
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  device_preview: ^3.0.0-prerelease3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/